### PR TITLE
Clarify PhpStorm setup instructions

### PR DESCRIPTION
**Pull request by danepowell**
Whenever I set up PhpCS integration with PhpStorm, I feel like I'm winging it and things fall through the cracks. Either I'm getting false positives from PhpStorm's built-in inspections that conflict with Acquia Coding Standards, or I've forgotten to turn on an important inspection like undefined function checks. It would be good to clearly prescribe how to set this up.

### CODE REVIEW

**Comment by TravisCarden** [comment]
Thanks, @danepowell. Do you really mean to recommend disabling _all_ of PhpStorm's built-in inspections? Because that seems excessive to me--there are _a lot_ of PhpStorm inspections that Acquia Coding Standards doesn't cover, including PHP code smell, PHP language level migration, and PHP probable bugs, for example. I wonder if you meant something more limited. I also wonder if the final recommendation is something that could be automated somehow. 🤔

**Comment by danepowell** [comment]
I wrote what I meant, to disable all built-in inspections. Now whether that's a good idea or not, that's up for debate 😄 

Even though there are some useful built-in inspections not handled by PHPCS, I find that they generate so many false positives that then have to be chased down (due to various peculiarities of Drupal architecture), that it's just not worth having them on in the first place. That's just my experience of course.

It would be awesome if we could come up with a list of the most beneficial and safe built-in inspections, and then create a configuration profile that people can import into PhpStorm so they don't have to turn them on/off individually. (this is supported via XML)

**Comment by TravisCarden** [comment]
@danepowell a default set of... PhpStorm inspections configuration XML? Hmm. I'm concerned that we may find ourselves "chasing HEAD", as it were, if we provide a full drop-in XML file. Any time PhpStorm changes the set of configurations or the XML schema we'll have an upgrade task and potentially a BC break. I don't know of a better solution off the top of my head (unless we could do some kind of XPath operations in a script). I just want to register my concern.

**Comment by danepowell** [comment]
Yeah okay, forget enabling/disabling built-in inspections. Still might be useful later, but not now.

This just provides an xml profile that will automatically set up PHPCS integration for you.

**Comment by TravisCarden** [comment]
Of course, I commented _right_ as you pushed code. :) If you can isolate the configuration as atomically as the PHP_Code_Sniffer only (as it appears you have), I would be much more open to that. That seems to match the scope of the project better.

**Comment by danepowell** [comment]
Related PhpStorm bug I discovered: https://youtrack.jetbrains.com/issue/WI-50455

**Comment by danepowell** [comment]
@TravisCarden you okay with merging this?

**Pull request merged**
